FROM php:8.4-fpm

# Installer les dépendances de base et les extensions PHP nécessaires
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libicu-dev \
    zip \
    libzip-dev \
    unzip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install intl pdo pdo_mysql mysqli gd zip gd exif \
    && docker-php-ext-enable pdo_mysql gd exif

# Donne les droits d'écriture dans le dossier
# RUN chown -R www-data:www-data /var/www/html
# RUN chmod -R 777 /var/www/html

# ???
# WORKDIR /var/www/api

# RUN php bin/console doctrine:migrations:migrate

# COPY entrypoint.sh /entrypoint.sh
# COPY ../docker/api/entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
# CMD ["php-fpm"]
