services:

  mysql:
    image: mysql:8.0
    container_name: bentoweb_mysql
    restart: always
    env_file:
      - .env
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_DATABASE: ${MYSQL_DATABASE_PROD}
      MYSQL_USER: ${MYSQL_USER_PROD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PROD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_PROD}
    volumes:
      - bentoweb_db_data:/var/lib/mysql
    networks:
      - bentoweb_network
      
  api:
    container_name: bentoweb_api
    image: ghcr.io/bentoweb-fr/skills2025-api:latest
    pull_policy: never
    environment:
      PUID: 1000
      PGID: 1000
      APP_ENV: prod
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_URL: "mysql://${MYSQL_USER_PROD}:${MYSQL_PASSWORD_PROD}@mysql:3306/${MYSQL_DATABASE_PROD}?serverVersion=8.0.32&charset=utf8mb4"
    #   build:
    #     context: ./api
    #     dockerfile: ../docker/api/Dockerfile
    volumes:
      # - ./api:/home/benoit/www/api
      # - /home/${USER}/www/api:/var/www/api
      - api_volume:/public
    networks:
      - bentoweb_network
    expose:
      - "9000"
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # front:
  #   container_name: skills2025-front
  #   image: ghcr.io/bentoweb-fr/skills2025-front:latest
  # build:
  #   context: ./front
  #   dockerfile: ../docker/front/Dockerfile
  # volumes:
  # - ./front:/var/www/front
  # - /var/www/front:/var/www/front
  # - ./:/var/www/front
  # environment:
  # PUID: 1000
  # PGID: 1000
  # NODE_ENV: prod
  #     VITE_API_URL: https://api.skills2025.local
  #     SHELL: /bin/ash # Fix chokidar-cli error
  # restart: unless-stopped
  # networks:
  #   - bentoweb_network
  # ports:
  #   - "3000:3000"

  nginx:
    image: ghcr.io/bentoweb-fr/skills2025-nginx:latest
    pull_policy: never
    # image: ghcr.io/${REGISTRY_USER}/skills2025-nginx:latest
    container_name: bentoweb_nginx
    volumes:
      #   - ./api:/var/www/api
      - api_volume:/var/www/api:ro
      - /home/${USER}/www/front:/var/www/front:ro
      - /home/${USER}/www/certs:/etc/nginx/ssl:ro
    # - /etc/letsencrypt:/etc/letsencrypt:ro
    # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # - ./nginx:/etc/nginx
    # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - bentoweb_network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      api:
        condition: service_healthy

  # phpmyadmin:
  #   image: phpmyadmin:5.2.1
  #   container_name: bentoweb_phpmyadmin
  #   restart: always
  #   ports:
  #     - 8022:80
  #   links:
  #     - mysql:mysql
  #   environment:
  #     PMA_HOST: mysql
  #   depends_on:
  #     - mysql
  #   networks:
  #     - bentoweb_network

networks:
  bentoweb_network:
    driver: bridge

volumes:
  api_volume:
  bentoweb_db_data:
    external: true
    name: bentoweb_db_data