services:

  mysql:
    image: mysql:8.0
    container_name: bentoweb_mysql
    restart: always
    env_file:
      - .env
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_DATABASE: ${MYSQL_DATABASE_PROD}
      MYSQL_USER: ${MYSQL_USER_PROD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PROD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_PROD}
    volumes:
      - bentoweb_db_data:/var/lib/mysql
    networks:
      - bentoweb_network

  api:
    container_name: bentoweb_api
    image: ghcr.io/bentoweb-fr/skills2025-api:${GITHUB_SHA}
    pull_policy: always
    environment:
      PUID: 1000
      PGID: 1000
      APP_ENV: prod
      DATABASE_URL: "mysql://${MYSQL_USER_PROD}:${MYSQL_PASSWORD_PROD}@mysql:3306/${MYSQL_DATABASE_PROD}?serverVersion=8.0.32&charset=utf8mb4"
    volumes:
      - api_volume:/var/www/api
    networks:
      - bentoweb_network
    expose:
      - "9000"
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: ghcr.io/bentoweb-fr/skills2025-nginx:latest
    pull_policy: never
    container_name: bentoweb_nginx
    volumes:
      - api_volume:/var/www/api:ro
      - /home/${USER}/www/front:/var/www/front:ro
      - /home/${USER}/www/certs:/etc/nginx/ssl:ro
    networks:
      - bentoweb_network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

# phpmyadmin:
#   image: phpmyadmin:5.2.1
#   container_name: bentoweb_phpmyadmin
#   restart: always
#   ports:
#     - 8022:80
#   links:
#     - mysql:mysql
#   environment:
#     PMA_HOST: mysql
#   depends_on:
#     - mysql
#   networks:
#     - bentoweb_network

networks:
  bentoweb_network:
    driver: bridge

volumes:
  api_volume:
    external: true
  bentoweb_db_data:
    external: true
    name: bentoweb_db_data