services:
  api:
    # container_name: skills2025_api
    image: ghcr.io/bentoweb-fr/skills2025/api
    pull_policy: never
    environment:
      PUID: 1000
      PGID: 1000
      APP_ENV: prod
  #   build:
  #     context: ./api
  #     dockerfile: ../docker/api/Dockerfile
    volumes:
      - ./api:/var/www/api
    networks:
      - bentoweb_network
    expose:
      - "9000"
    depends_on:
      - mysql

  # front:
  #   container_name: skills2025_front
    # image: skills2025/front:latest
  #   build:
  #     context: ./front
  #     dockerfile: ../docker/front/Dockerfile
  #   volumes:
  #     - ./front:/var/www/front
  #   environment:
  #     PUID: 1000
  #     PGID: 1000
  #     NODE_ENV: prod
  # #     VITE_API_URL: https://api.skills2025.local
  # #     SHELL: /bin/ash # Fix chokidar-cli error
  #   restart: unless-stopped
  #   networks:
  #     - bentoweb_network
  #   ports:
  #     - "3000:3000"

  nginx:
    image: ghcr.io/bentoweb-fr/skills2025-nginx
    pull_policy: never
    # image: ghcr.io/${REGISTRY_USER}/skills2025-nginx:latest
    # container_name: skills2025_nginx
    volumes:
      #   - ./api:/var/www/api
      - /var/www/front:/var/www/front
      - ./nginx:/etc/nginx
    networks:
      - bentoweb_network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      # - front

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: skills2025
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - bentoweb_db_data:/var/lib/mysql

# phpmyadmin:
#   image: phpmyadmin:5.2.1
#   container_name: skills2025_phpmyadmin
#   restart: always
#   ports:
#     - 8022:80
#   links:
#     - mysql:mysql
#   environment:
#     PMA_HOST: mysql
#   depends_on:
#     - mysql
#   networks:
#     - bentoweb_network

networks:
  bentoweb_network:
    driver: bridge

volumes:
  bentoweb_db_data:
    external: true
    name: bentoweb_db_data