services:

  mysql:
    image: mysql:8.0
    container_name: skills2025_mysql
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - skills2025_network
  api:
    container_name: skills2025_api
    environment:
      PUID: 1000
      PGID: 1000
      APP_ENV: ${APP_ENV}
      API_DATABASE_USER: ${API_DATABASE_USER}
      API_DATABASE_PASSWORD: ${API_DATABASE_PASSWORD}
      API_DATABASE_NAME: ${API_DATABASE_NAME}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./api:/var/www/api
    networks:
      - skills2025_network
    expose:
      - "9000"
    depends_on:
      - mysql

  front:
    container_name: skills2025_front
    build:
      context: ./front
      dockerfile: ../docker/front/Dockerfile
    volumes:
      - ./front:/var/www/front
    environment:
      PUID: 1000
      PGID: 1000
      NODE_ENV: dev
      SHELL: /bin/ash # Fix chokidar-cli error
      VITE_PORT: ${URL_FRONT_VITE_PORT}
    restart: unless-stopped
    networks:
      - skills2025_network
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"

  nginx:
    image: nginx:stable
    container_name: skills2025_nginx
    environment:
      - FRONT_DOMAIN=${LOCAL_FRONT_DOMAIN}
      - API_DOMAIN=${LOCAL_API_DOMAIN}
    volumes:
      - ./api:/var/www/api
      - ./front/public:/var/www/front
      - ./nginx:/etc/nginx
    networks:
      - proxy
      - skills2025_network
    # ports:
    #   - "80:80"
    #   - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # Router pour skills2025.local (front) - HTTP
      - "traefik.http.routers.skills2025-front.rule=Host(`skills2025.local`)"
      - "traefik.http.routers.skills2025-front.entrypoints=web"
      - "traefik.http.routers.skills2025-front.service=skills2025-nginx"
      # Router pour skills2025.local (front) - HTTPS
      - "traefik.http.routers.skills2025-front-secure.rule=Host(`skills2025.local`)"
      - "traefik.http.routers.skills2025-front-secure.entrypoints=websecure"
      - "traefik.http.routers.skills2025-front-secure.service=skills2025-nginx"
      - "traefik.http.routers.skills2025-front-secure.tls.options=default"
      # Router pour api.skills2025.local - HTTP
      - "traefik.http.routers.skills2025-api.rule=Host(`api.skills2025.local`)"
      - "traefik.http.routers.skills2025-api.entrypoints=web"
      - "traefik.http.routers.skills2025-api.service=skills2025-nginx"
      # Router pour api.skills2025.local - HTTPS
      - "traefik.http.routers.skills2025-api-secure.rule=Host(`api.skills2025.local`)"
      - "traefik.http.routers.skills2025-api-secure.entrypoints=websecure"
      - "traefik.http.routers.skills2025-api-secure.service=skills2025-nginx"
      # - "traefik.http.routers.skills2025-api-secure.tls.options=default"
      # Service nginx (port 80 dans le container)
      - "traefik.http.services.skills2025-nginx.loadbalancer.server.scheme=https"
      - "traefik.http.services.skills2025-nginx.loadbalancer.server.port=443"
    depends_on:
      - api
      - front
    # entrypoint: ["/entrypoint.sh"]

  # phpmyadmin:
  #   image: phpmyadmin:5.2.1
  #   container_name: skills2025_phpmyadmin
  #   restart: always
  #   ports:
  #     - 8022:80
  #   links:
  #     - mysql:mysql
  #   environment:
  #     PMA_HOST: mysql
  #   depends_on:
  #     - mysql
  #   networks:
  #     - skills2025_network

networks:
  skills2025_network:
    driver: bridge
  proxy:
    external: true

volumes:
  api_volume:
  mysql_data:
    external: true
    name: skills2025_mysql_data