api_platform:
  defaults:
    route_prefix: /api
    # pagination_enabled: false
    pagination_items_per_page: 3 # Default value
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  enable_docs: true
  # collection:
  #   pagination:
  #     page_parameter_name: _page