FROM node:20-alpine AS build

# WORKDIR /app
# WORKDIR /
# COPY package*.json ./

# COPY ./front/package.json package-lock.json ./
# COPY --from=build /front/public /usr/share/nginx/html

# COPY ./ ./

# RUN npm ci

# RUN npm run dev

# RUN npm run build
